[project]
name = "LoIK"
version = "1.0.0"
description = "LoIK is a simple yet efficient (constrained) differential inverse kinematics solver for robotics"
authors = ["Bruce Wingo <wingobruce47@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "osx-arm64", "win-64"]
license = "BSD-2-Clause"
license-file = "LICENSE"

[tasks]
configure = { cmd = ["cmake", "-G", "Ninja", "-B", "build", "-S", "."] }
build = { cmd = "cmake --build build --target all", depends_on = ["configure"] }
clean = { cmd = "rm -rf build" }
test = { cmd = "ctest --test-dir build --output-on-failure", depends_on = [
  "build",
] }

[build-dependencies]
ccache = ">=4.9.1,<4.10"
cxx-compiler = ">=1.7.0,<1.8"
pkg-config = ">=0.29.2,<0.30"
cmake = ">=3.29.6,<3.31"
ninja = ">=1.12.1,<1.13"

[dependencies]
eigen = ">=3.4.0,<3.5"
pinocchio = ">=3.0.0,<3.2"
boost = ">=1.84.0,<1.85"
example-robot-data = ">=4.1.0,<4.2"

[activation]
scripts = ["scripts/activation.sh"]

[target.win-64.activation]
scripts = ["scripts/activation.bat"]

[feature.clang-cl]
platforms = ["win-64"]

[feature.clang-cl.activation]
scripts = ["scripts/activation_clang.bat"]

[environments]
clang-cl = { features = ["clang-cl"] }
