name: CI - Check-changelog

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened, labeled, unlabeled, edited]
    branches:
      - devel
jobs:
  check-changelog:
    name: Check changelog action
    runs-on: ubuntu-latest
    steps:
      - uses: tarides/changelog-check-action@v2
        with:
          changelog: CHANGELOG.md
